# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/delos3geur/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/delos3geur/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/delos3geur/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/delos3geur/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/samsung/delos3geur/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/samsung/delos3geur/proprietary/bin/bccmd:system/bin/bccmd \
    vendor/samsung/delos3geur/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/samsung/delos3geur/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/delos3geur/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/samsung/delos3geur/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/samsung/delos3geur/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/delos3geur/proprietary/lib/libdbus.so:system/lib/libdbus.so \
    vendor/samsung/delos3geur/proprietary/lib/libbluetooth.so:system/lib/libbluetooth.so \
    vendor/samsung/delos3geur/proprietary/lib/libbluetoothd.so:system/lib/libbluetoothd.so \
    vendor/samsung/delos3geur/proprietary/lib/libbtio.so:system/lib/libbtio.so \
    vendor/samsung/delos3geur/proprietary/bin/lpmkey:system/bin/lpmkey \
    vendor/samsung/delos3geur/proprietary/bin/playlpm:system/bin/playlpm \
    vendor/samsung/delos3geur/proprietary/bin/gpu_dcvsd:system/bin/gpu_dcvsd \
    vendor/samsung/delos3geur/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/samsung/delos3geur/proprietary/bin/qosmgr:system/bin/qosmgr \
    vendor/samsung/delos3geur/proprietary/etc/init.ath3k.bt.sh:system/etc/init.ath3k.bt.sh \
    vendor/samsung/delos3geur/proprietary/etc/init.qcom.bt.sh:system/etc/init.qcom.bt.sh \
    vendor/samsung/delos3geur/proprietary/etc/init.qcom.coex.sh:system/etc/init.qcom.coex.sh \
    vendor/samsung/delos3geur/proprietary/etc/init.qcom.composition_type.sh:system/etc/init.qcom.composition_type.sh \
    vendor/samsung/delos3geur/proprietary/etc/init.qcom.efs.sync.sh:system/etc/init.qcom.efs.sync.sh \
    vendor/samsung/delos3geur/proprietary/etc/init.qcom.fm.sh:system/etc/init.qcom.fm.sh \
    vendor/samsung/delos3geur/proprietary/etc/init.qcom.post_boot.sh:system/etc/init.qcom.post_boot.sh \
    vendor/samsung/delos3geur/proprietary/etc/init.qcom.post_fs.sh:system/etc/init.qcom.post_fs.sh \
    vendor/samsung/delos3geur/proprietary/etc/init.qcom.sdio.sh:system/etc/init.qcom.sdio.sh \
    vendor/samsung/delos3geur/proprietary/etc/init.qcom.thermald_conf.sh:system/etc/init.qcom.thermald_conf.sh \
    vendor/samsung/delos3geur/proprietary/etc/init.qcom.wifi.sh:system/etc/init.qcom.wifi.sh \
    vendor/samsung/delos3geur/proprietary/etc/init.target.8x25.sh:system/etc/init.target.8x25.sh \
    vendor/samsung/delos3geur/proprietary/etc/PSConfig_7820.psr:system/etc/PSConfig_7820.psr \
    vendor/samsung/delos3geur/proprietary/etc/param.dat:system/etc/param.dat \
    vendor/samsung/delos3geur/proprietary/etc/thermald-8x25-msm1-pmic_therm.conf:system/etc/thermald-8x25-msm1-pmic_therm.conf \
    vendor/samsung/delos3geur/proprietary/etc/thermald-8x25-msm2-msm_therm.conf:system/etc/thermald-8x25-msm2-msm_therm.conf \
    vendor/samsung/delos3geur/proprietary/etc/thermald-8x25-msm2-pmic_therm.conf:system/etc/thermald-8x25-msm2-pmic_therm.conf \
    vendor/samsung/delos3geur/proprietary/etc/vold.fstab:system/etc/vold.fstab
